### ISSUE TITLE
Milestone 1 Agenda

### ISSUE THREAD

**Issue by tdkhanhvu** [UBC-MDS/pygtracker#1]
## I) Task breakdown
[Canvas submission instruction](https://canvas.ubc.ca/courses/59081/assignments/842237)

|#|Task|Marks|Description|Deliverables|Assignee|
|--|--|--|--|--|--|
|1|Working style (10%)|mechanics:10|<ul><li>Commit to git every time you work on this project with meaningful messages (graded)</li><li>Follow branching approach (Create branch -> Push commits -> Create Pull Request -> Reviewed and approved by another person)</li><li>Use GitHub for project-related communication</li><li>Use proper grammar and full sentences throughout the project, especially in your README.</li></ul>||TBD|
|2|Follow Submission Instruction (10%)|mechanics:10|<ul><li>Include the URL of your public project’s repo</li><li>Include the URL to a release on your project repo named v0.1.0</li><li>Include a link to your team work document that is accessible to the teaching team</li></ul>|canvas-submission.html|TBD|
|3|Teamwork contract (10%)|correctness:10|Similar to 522|Google Docs link in the submission file|TBD|
|4|Pick a topic||Discuss the topic with your TA or lab instructor and proceed only after your topic has been approved by one of them|Topic chosen|TBD|
|5|Create project structure for the Python project (40%)|mechanics:40|<ul><li>Create project structure & push it as a public repository in the UBC-MDS organization on Github.com</li><li>Choose a relevant name</li><li>Choose MIT license (can change later)</li><li>Add the contributor names to `CONTRIBUTORS.md`</li><li>Add code of conduct to `CONDUCT.md`</li><li>Agree upon a collaboration strategy and edit `CONTRIBUTING.md`</li><li>Outline the package you would like to build in the `README.md` file</li></ul>|<ul><li>`LICENSE.txt`</li><li>`/CONTRIBUTORS.md`</li><li>`/CONDUCT.md`</li><li>`/CONTRIBUTING.md`</li><li>`/README.md`</li></ul>|TBD|
|6|Function specifications (20%)|quality:20|<ul><li>Set up empty functions (with appropriate names) containing no code in the files where you will eventually write code.</li><li>Write function documentation (e.g., complete docstrings).</li></ul>|Empty functions with documentation|TBD|
|7|Manage issues (10%)|mechanics:10|Create an issue for each function in the package for one person|Github issues|TBD|

### 1) Choose a topic:

Each person
- Comes up with 1 topic for discussion, including functions to be implemented
- Posts in a Github issue and comments on others' topics

Team:
- Discuss, finalize during lab time and ask for TA's approval.

### 2) Teamwork contract:

Agree on below points:
- Deadline to finish the tasks given
- Availability for team meeting
- People take turns to do the release
- Rotate reviewers for each person's work every week
- ...

## III) Tentative deadlines for this week:
(Can be adjusted after our discussion)
- Thursday 9AM: Topics + functions proposed (Pros + Cons if possible)
- Thursday 2PM: Feedback on other's topics and functions
- Thursday 4PM (after lab): Topic finalized and tasks assigned
- Saturday 9AM: All tasks completed
- Saturday 2PM: All tasks reviewed and merged
- Saturday 5PM: Milestone submitted on Canvas and released on Github

## IV) Tentative workflow for this week:

Tue - Thu 9AM:
- Finalize teamwork contract
- Create Github issues

Thu 4PM - Fri 9AM:
- 1 person: Create project structure skeleton (name depends on the topic). @tdkhanhvu can volunteer.
- Others: Work on other documentation files in the projects (`README.md`, `CONDUCT.md`...) (put in notepad or temporary project and update in the real project later)

Fri 9AM - Sat 9AM:
- Work on function specifications (1 person / 1 function / 1 github issue)

**Comment by jraza19** [comment]
The following tasks have been completed by the team for this milestone.
