### ISSUE TITLE
Milestone 2 Agenda

### ISSUE THREAD

**Issue by tdkhanhvu** [UBC-MDS/pygtracker#29]
## I) Task breakdown
[Canvas submission instruction](https://canvas.ubc.ca/courses/59081/assignments/842238)

|#|Task|Marks|Description|Deliverables|Assignee|
|--|--|--|--|--|--|
|1|Working style (10%)|mechanics:10|<ul><li>Commit to git every time you work on this project with meaningful messages (graded)</li><li>Follow branching approach (Create branch -> Push commits -> Create Pull Request -> Reviewed and approved by another person)</li><li>Use GitHub for project-related communication</li><li>Use proper grammar and full sentences throughout the project, especially in your README.</li></ul>||TBD|
|2|Follow Submission Instruction (10%)|mechanics:10|<ul><li>The URL for each of your your public projects’ repositories</li><li>The URL to a release for each of your projects repositories</li></ul>|canvas-submission.html|TBD|
|3|**Python** - Write test cases and code iteratively (40%)|accuracy:20<br>quality:10<br>mechanics:10|<ul><li>Revisit function specifications & revise</li><li>Write unit tests for 3 to 5 edge cases / function and name them after the function being tested (`foo` -> `test_foo`)</li><li>Write the internal code for Python functions.</li><li>Follow this flow: tests → function improvement → writing more tests → function improvement...</li><li>Make sure that the tests cover all branches</li><li>Update code documentation and document unit tests</li><li>Use `pytest` package to run those tests</li></ul>|<ul><li>Unit tests written</li><li>Code documentation updated</li><li>Unit tests documented</li></ul>|TBD|
|4|**Python** - Exception handling (10%)|quality:10|<ul><li>Codes handle incorrect input and errors detected during execution</li><li>Codes throw exceptions with useful error messages</li><li>Tests confirm that the exceptions result  in the expected behaviour of the function</li></ul>|Defensive Codes|TBD|
|5|**R** - Create project structure (20%)|mechanics:20|<ul><li>Create project structure & push it as a public repository in the UBC-MDS organization on Github.com</li><li>Choose a relevant name</li><li>Choose MIT license (can change later)</li><li>Add code of conduct via `usethis::use_code_of_conduct`</li><li>Add the team members as authors to the `DESCRIPTION` file</li><li>Add `CONTRIBUTING.md` file via `usethis::use_tidy_contributing()` and reflect contribution strategy agreed upon</li><li>Outline the package you would like to build in the `README.md` file</li></ul>|<ul><li>`LICENSE.txt`</li><li>`/DESCRIPTION`</li><li>`/CONDUCT.md`</li><li>`/CONTRIBUTING.md`</li><li>`/README.md`</li></ul>|TBD|
|6|**R** - Function specifications (10%)|quality:10|<ul><li>Set up empty functions (with appropriate names) containing no code in the files where you will eventually write code.</li><li>Write function documentation (e.g., complete roxygen2 ).</li></ul>|Empty functions with documentation|TBD|

### 1) Python

- Write unit tests
- Implement functions

### 2) R

- Setup an empty project
- Write Roxygen2 without codes

## III) Tentative deadlines for this week:
(Can be adjusted after our discussion)
- Thursday 9AM: Python Code + Unit Tested Finished
- Thursday 2PM: Feedback on other's codes and unit tests
- Thursday 11:59PM: R empty project setup
- Friday 11:59PM: R Roxygen documentation finished
- Saturday 2PM: All tasks reviewed and merged
- Saturday 5PM: Milestone submitted on Canvas and released on Github

## IV) Tentative workflow for this week:

Tue - Thu 9AM:
- Write unit tests for **Python**
- Write code implementation for **Python**

Thu 4PM - Thu 11:59PM:
- 1 person: Create project structure skeleton for **R** (name depends on the topic). `rgtracker`?
- Others: Work on feedback for **Python** codes and unit tests

Fri 0AM - Fri 11:59PM:
- Work on function specifications for **R**

**Comment by jraza19** [comment]
Tasks completed and reviewed at team meeting (March 6)
