### ISSUE TITLE
meeting minute March 2

### ISSUE THREAD

**Issue by jianructose** [UBC-MDS/pygtracker#31]
- generated 2 toy dataset saved in data directory
- first function: check the df has correct cols; all assessments sum up to be 1 and each one should be (0, 1)
- 2nd fn: check df has correct cols; grade should be in (0, 100); 
- 3rd fn: check the course_id exists, stats values are correct
- `rank_courses` : stats should be one of the four; `descending/ascending` should work; 
- `rank_students`: course_id does exist;  n should be <=total # of; `descending/ascending`should work; output should have proper cols(cols#, type, value, name of cols);
- `suggest_grade_adjustment`: check all benchmark should be (0, 1); test for no adjustment; tests for each benchmark
(feel free to edit as you need)

**Comment by tdkhanhvu** [comment]
Format of the data in memory:

**Courses**
course_id | lab1 | lab2 | lab3 | quiz1
-- | -- | -- | -- | --
511 | 0.15 | 0.15 | 0.15 | 0.2
512 | 0.15 | 0.15 | 0.15 | 0.2

**Grades**
course_id | student_id | lab1 | lab2 | lab3 | quiz1
-- | -- | -- | -- | -- | --
511 | StudentA | 80 | 80 | 80 | 80
512 | StudentB | 90 | 80 | 80 | 80

**Comment by jraza19** [comment]
Tasks implemented in functions!
