### ISSUE TITLE
Function - Summarize the grades by course

### ISSUE THREAD

**Issue by yhchen20** [UBC-MDS/pygtracker#6]
Purpose:
Provides summary statistics on the courses 
Lecturers can benchmark the difficulty based on the average grades for all courses 

Input - 
        method (default = summary, across_summary)
        
Output:
        summary: summary statistics on each course - Mean / Median / Quantile 1,2,3,4
        across_summary: based on average grade for each course, rank the courses in the decreasing order

Some Ideas about the function:
For each students, calculate the overall grade by using the studnets grades and the corresponding assignment assessments (each course has different assessments and different number of assignment)
Store them into a dataframe (each row represents a student and each column represent a course)
Calculate summary statistics for each course
Print the output based on the method

**Comment by jraza19** [comment]
Issue will be closed after Milestone 2.
