### ISSUE TITLE
Function - Suggest grade adjustment

### ISSUE THREAD

**Issue by tdkhanhvu** [UBC-MDS/pygtracker#8]
**Purpose:**
Based on a predefined benchmark (90% for each lab, 90% for whole course, 85% for quiz), suggest grade adjustments for any course and return the suggested grades.

**Input** - three benchmark variables (course, lab, quiz), course ID
**Output** - summary table with suggested grade adjustment

function(courseid, benchmark_course = 0.9, benchmark_lab = 0.85, benchmark_quiz = 0.85)

**Comment by jraza19** [comment]
Issue should not be closed until Milestone 2.

**Comment by jraza19** [comment]
implementation completed!
